version: "3"
services:
  mssql:
    build:
      context: .
      dockerfile: .Dockerfile
    image: our_database
    environment:
      - SA_PASSWORD=qMPsf7gqJzrdNtdjN
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
